version: "3.2"
services:



  # rs-sh1
  rs-sh1-01:
    image: mongo:4.4.4
    container_name: rs-sh1-01
    volumes:
      - rs-sh1-01:/data/db
    expose:
    - 27017
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27017", "--replSet", "rs-sh1", "--shardsvr" ]
  rs-sh1-02:
    image: mongo:4.4.4
    container_name: rs-sh1-02
    volumes:
      - rs-sh1-02:/data/db
    expose:
    - 27012
    ports:
    - 27012:27012
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27012", "--replSet", "rs-sh1", "--shardsvr" ]
  rs-sh1-03:
    image: mongo:4.4.4
    container_name: rs-sh1-03
    volumes:
      - rs-sh1-03:/data/db
    expose:
    - 27013
    ports:
    - 27013:27013
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27013", "--replSet", "rs-sh1", "--shardsvr" ]
  
  backend:
    build: ./API
    ports:
      - "3000:3000"
    depends_on:
      - rs-sh1-01

  frontend:
    build: ./Web/front-bds
    ports:
      - "5173:5173"
    depends_on:
    - backend
    
volumes:
  rs-sh1-01:
  rs-sh1-02:
  rs-sh1-03: